"""Catálogo oficial de riesgos — Anexo 2 CR del formato MATRIZ IPER (Guía ISP 3) V3.3 · D.S. 44.

57 riesgos específicos con su código normativo, agrupados en 4 familias. Dato puro, como fuf.py:
no toca la BD ni Flask.

GENERADO desde el Excel oficial y verificado fila por fila contra él — no transcrito a mano. El
mismo método de fuf.py: una errata en una definición normativa no se detecta leyendo.

La clave de diseño: cada familia del Anexo 2 corresponde a UNA de las cuatro evaluaciones que el
formato exige por fila (columnas H-S). Por eso `tipo` no se elige: lo dicta el catálogo.

  RIESGOS DE SEGURIDAD          → 'seguridad'    (Seguridad y emergencias, cols H-J)
  RIESGOS HIGIÉNICOS            → 'higienico'    (Higiénicos, cols K-M)
  RIESGOS PSICOSOCIALES         → 'psicosocial'  (Psicosociales, cols N-P)
  RIESGOS MÚSCULO ESQUELÉTICOS  → 'musculo'      (Músculo esqueléticos, cols Q-S)

NOTA: el Anexo 2 NO trae medidas de control, solo la definición del riesgo. Las medidas las
escribe el prevencionista (ver matriz_riesgos): son contenido preventivo con peso legal y el
sistema tiene prohibido inventarlas.
"""

TIPOS = {
    'seguridad': 'Seguridad y emergencias',
    'higienico': 'Higiénicos',
    'psicosocial': 'Psicosociales',
    'musculo': 'Músculo esqueléticos',
}

RIESGOS = [
    {'codigo': 'A1', 'tipo': 'seguridad',
     'familia': 'Caída de personas',
     'riesgo': 'Caídas al mismo nivel',
     'definicion': 'Caída que se produce en el mismo plano de sustentación.'},
    {'codigo': 'A2', 'tipo': 'seguridad',
     'familia': 'Caída de personas',
     'riesgo': 'Caídas a distinto nivel',
     'definicion': 'Caída a un plano inferior desde menos de 1.8 mts.'},
    {'codigo': 'A3', 'tipo': 'seguridad',
     'familia': 'Caída de personas',
     'riesgo': 'Caídas de altura',
     'definicion': 'Caída a un plano inferior desde más de 1.8 mts.'},
    {'codigo': 'A4', 'tipo': 'seguridad',
     'familia': 'Caída de personas',
     'riesgo': 'Caídas al agua',
     'definicion': 'Caída a un curso de agua natural o estructura con agua.'},
    {'codigo': 'B1', 'tipo': 'seguridad',
     'familia': 'Contacto con objetos',
     'riesgo': 'Atrapamiento',
     'definicion': 'Enganche o aprisionamiento del cuerpo, o parte de éste, por mecanismos de las máquinas, objetos, piezas, materiales, equipos o vehículos que han perdido su estabilidad.'},
    {'codigo': 'B2', 'tipo': 'seguridad',
     'familia': 'Contacto con objetos',
     'riesgo': 'Caída de objetos',
     'definicion': 'Caída de elementos que golpean al cuerpo, por ejemplo, materiales, herramientas, estructuras, etc.'},
    {'codigo': 'B3', 'tipo': 'seguridad',
     'familia': 'Contacto con objetos',
     'riesgo': 'Cortes por objetos/herramientas cortopunzantes',
     'definicion': 'Cortes y/o punzaciones generadas en parte del cuerpo debido al contacto de éste con objetos cortantes, punzantes y/o abrasivos.'},
    {'codigo': 'B4', 'tipo': 'seguridad',
     'familia': 'Contacto con objetos',
     'riesgo': 'Choque contra objetos',
     'definicion': 'Encuentro violento del cuerpo, o de una parte de éste, con uno o varios objetos, estén éstos en movimiento o no.'},
    {'codigo': 'C1', 'tipo': 'seguridad',
     'familia': 'Contacto con seres vivos',
     'riesgo': 'Contacto con personas',
     'definicion': 'Lesiones recibidas en el cuerpo, o parte de éste (agresiones, patadas, mordiscos, etc.) debido a la acción de otras personas.'},
    {'codigo': 'C2', 'tipo': 'seguridad',
     'familia': 'Contacto con seres vivos',
     'riesgo': 'Contacto con animales y/o insectos',
     'definicion': 'Lesiones recibidas en el cuerpo, o parte de éste (arañazos, patadas, mordiscos, etc.) debido a la interacción con animales y/o insectos.'},
    {'codigo': 'E1', 'tipo': 'seguridad',
     'familia': 'Contactos térmicos',
     'riesgo': 'Contactos térmicos por calor',
     'definicion': 'Acción y efecto de hacer contacto físico con superficies o productos calientes.'},
    {'codigo': 'E2', 'tipo': 'seguridad',
     'familia': 'Contactos térmicos',
     'riesgo': 'Contactos térmicos por frío',
     'definicion': 'Contacto físico con superficies o productos fríos.'},
    {'codigo': 'F1', 'tipo': 'seguridad',
     'familia': 'Contacto con energía eléctrica',
     'riesgo': 'Contactos eléctricos directos baja tensión',
     'definicion': 'Contacto directo con partes activas en tensión (<1000 volts).'},
    {'codigo': 'F2', 'tipo': 'seguridad',
     'familia': 'Contacto con energía eléctrica',
     'riesgo': 'Contactos eléctricos directos alta tensión',
     'definicion': 'Contacto directo con partes activas en tensión (>1000 volts).'},
    {'codigo': 'F3', 'tipo': 'seguridad',
     'familia': 'Contacto con energía eléctrica',
     'riesgo': 'Contactos eléctricos indirectos baja tensión',
     'definicion': 'Contacto con masas accidentalmente en tensión (<1000 volts).'},
    {'codigo': 'F4', 'tipo': 'seguridad',
     'familia': 'Contacto con energía eléctrica',
     'riesgo': 'Contactos eléctricos indirectos alta tensión',
     'definicion': 'Contacto con masas accidentalmente en tensión (>1000 volts).'},
    {'codigo': 'G1', 'tipo': 'seguridad',
     'familia': 'Contacto con sustancias químicas',
     'riesgo': 'Contacto con sustancias cáusticas y/o corrosivas',
     'definicion': 'Contacto con sustancias cáusticas que causan lesiones en la piel.'},
    {'codigo': 'G2', 'tipo': 'seguridad',
     'familia': 'Contacto con sustancias químicas',
     'riesgo': 'Contacto con otras sustancias químicas',
     'definicion': 'Contacto con sustancias no cáusticas que causan lesiones en la piel.'},
    {'codigo': 'H1', 'tipo': 'seguridad',
     'familia': 'Contacto con elementos que se proyectan',
     'riesgo': 'Explosiones',
     'definicion': 'Liberación brusca de energía que genera presión y calor.'},
    {'codigo': 'H2', 'tipo': 'seguridad',
     'familia': 'Contacto con elementos que se proyectan',
     'riesgo': 'Proyección de fragmentos y/o partículas',
     'definicion': 'Contacto violento con fragmentos proyectados como piezas o partículas.'},
    {'codigo': 'I1', 'tipo': 'seguridad',
     'familia': 'Contacto con/en Vehículos en movimiento',
     'riesgo': 'Atropellos o golpes con vehículos',
     'definicion': 'Impacto entre peatón y vehículo en movimiento.'},
    {'codigo': 'I2', 'tipo': 'seguridad',
     'familia': 'Contacto con/en Vehículos en movimiento',
     'riesgo': 'Choque, colisión o volcamiento',
     'definicion': 'Lesiones por choque, colisión o volcamiento de vehículos.'},
    {'codigo': 'J', 'tipo': 'seguridad',
     'familia': 'Incendios',
     'riesgo': 'Incendios',
     'definicion': 'Fuego incontrolado que genera lesiones por gases o altas temperaturas.'},
    {'codigo': 'K1', 'tipo': 'seguridad',
     'familia': 'Exposición a condiciones atmosféricas extremas',
     'riesgo': 'Exposición a ambientes con deficiencia de oxígeno',
     'definicion': 'Exposición a atmósfera con déficit de oxígeno (<19.5%).'},
    {'codigo': 'K2', 'tipo': 'seguridad',
     'familia': 'Exposición a condiciones atmosféricas extremas',
     'riesgo': 'Exposición a sustancias químicas tóxicas',
     'definicion': 'Exposición a atmósfera con altas concentraciones de químicos tóxicos.'},
    {'codigo': 'L1', 'tipo': 'seguridad',
     'familia': 'Exposición a altos niveles de radiación',
     'riesgo': 'Exposición a radiaciones no ionizantes',
     'definicion': 'Exposición a altas dosis de radiaciones no ionizantes (UV, IR, etc.).'},
    {'codigo': 'L2', 'tipo': 'seguridad',
     'familia': 'Exposición a altos niveles de radiación',
     'riesgo': 'Exposición a radiaciones ionizantes',
     'definicion': 'Exposición a altas dosis de radiaciones ionizantes (rayos X, gamma).'},
    {'codigo': 'M', 'tipo': 'seguridad',
     'familia': 'Ingesta de sustancias nocivas',
     'riesgo': 'Ingesta de sustancias nocivas',
     'definicion': 'Ingesta de sustancias que alteran la salud del trabajador.'},
    {'codigo': 'N', 'tipo': 'seguridad',
     'familia': 'Otros riesgos',
     'riesgo': 'Otros riesgos',
     'definicion': 'Riesgos no descritos en ítems anteriores.'},
    {'codigo': 'O1', 'tipo': 'higienico',
     'familia': 'Exposición a agentes químicos',
     'riesgo': 'Exposición a aerosoles sólidos',
     'definicion': 'Permanencia en ambientes con partículas sólidas en suspensión.'},
    {'codigo': 'O2', 'tipo': 'higienico',
     'familia': 'Exposición a agentes químicos',
     'riesgo': 'Exposición a aerosoles líquidos',
     'definicion': 'Permanencia en ambientes con partículas líquidas en suspensión.'},
    {'codigo': 'O3', 'tipo': 'higienico',
     'familia': 'Exposición a agentes químicos',
     'riesgo': 'Exposición a gases y vapores',
     'definicion': 'Permanencia en ambientes con sustancias en estado gaseoso.'},
    {'codigo': 'P1', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a ruido',
     'definicion': 'Permanencia en ambientes con altos niveles de presión sonora.'},
    {'codigo': 'P2', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a Vibraciones',
     'definicion': 'Permanencia en ambientes con energía vibratoria transferida al cuerpo.'},
    {'codigo': 'P3', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a Radiaciones Ionizantes',
     'definicion': 'Permanencia en ambientes con radiaciones ionizantes.'},
    {'codigo': 'P4', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a Radiaciones No Ionizantes',
     'definicion': 'Permanencia en ambientes con radiaciones no ionizantes.'},
    {'codigo': 'P5', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a Calor',
     'definicion': 'Permanencia en ambientes con altas temperaturas.'},
    {'codigo': 'P6', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a Frío',
     'definicion': 'Permanencia en ambientes con bajas temperaturas.'},
    {'codigo': 'P7', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a Altas presiones',
     'definicion': 'Permanencia en ambientes con presiones superiores a la atmosférica.'},
    {'codigo': 'P8', 'tipo': 'higienico',
     'familia': 'Exposición a agentes físicos',
     'riesgo': 'Exposición a Bajas presiones',
     'definicion': 'Permanencia en ambientes con presiones inferiores a la atmosférica.'},
    {'codigo': 'Q1', 'tipo': 'higienico',
     'familia': 'Exposición a agentes biológicos',
     'riesgo': 'Transmisión por sangre y fluidos',
     'definicion': 'Inoculación de agentes biológicos por sangre o fluidos.'},
    {'codigo': 'Q2', 'tipo': 'higienico',
     'familia': 'Exposición a agentes biológicos',
     'riesgo': 'Transmisión aérea, hídrica y por contacto',
     'definicion': 'Exposición a agentes biológicos por transmisión aérea, hídrica o por contacto.'},
    {'codigo': 'R1', 'tipo': 'musculo',
     'familia': 'Manejo o Manipulación Manual de Carga (MMC) o Personas (MMP)',
     'riesgo': 'Sobrecarga física debido a la manipulación manual de cargas',
     'definicion': 'Trabajos que implican levantar, descender o transportar manualmente objetos de más de 3 kg.'},
    {'codigo': 'R2', 'tipo': 'musculo',
     'familia': 'Manejo o Manipulación Manual de Carga (MMC) o Personas (MMP)',
     'riesgo': 'Sobrecarga física debido a la manipulación de personas/pacientes',
     'definicion': 'Trabajos que implican manejo manual de personas/pacientes.'},
    {'codigo': 'S1', 'tipo': 'musculo',
     'familia': 'Trabajo repetitivo de la extremidad superior',
     'riesgo': 'Sobrecarga física debido al trabajo repetitivo de las extremidades superiores',
     'definicion': 'Tareas que implican movimientos repetitivos de las extremidades superiores.'},
    {'codigo': 'T1', 'tipo': 'musculo',
     'familia': 'Sobrecarga Postural (postura mantenida y/o forzada)',
     'riesgo': 'Sobrecarga Postural debido a trabajo de pie',
     'definicion': 'Trabajos en posición bípeda permanente con escasa alternancia postural.'},
    {'codigo': 'T2', 'tipo': 'musculo',
     'familia': 'Sobrecarga Postural (postura mantenida y/o forzada)',
     'riesgo': 'Sobrecarga Postural debido a trabajo sentado',
     'definicion': 'Trabajos en posición sentado mantenido por períodos prolongados.'},
    {'codigo': 'T3', 'tipo': 'musculo',
     'familia': 'Sobrecarga Postural (postura mantenida y/o forzada)',
     'riesgo': 'Sobrecarga Postural debido a trabajo en cuclillas (agachado)',
     'definicion': 'Trabajos en posición de cuclillas por tiempos prolongados.'},
    {'codigo': 'T4', 'tipo': 'musculo',
     'familia': 'Sobrecarga Postural (postura mantenida y/o forzada)',
     'riesgo': 'Sobrecarga Postural debido a trabajo arrodillado',
     'definicion': 'Trabajos que implican compresión directa sobre las rodillas sostenidamente.'},
    {'codigo': 'T5', 'tipo': 'musculo',
     'familia': 'Sobrecarga Postural (postura mantenida y/o forzada)',
     'riesgo': 'Sobrecarga Postural debido a tronco inclinado, en torsión o lateralización',
     'definicion': 'Trabajos con posturas del tronco fuera del rango neutro o de confort.'},
    {'codigo': 'T6', 'tipo': 'musculo',
     'familia': 'Sobrecarga Postural (postura mantenida y/o forzada)',
     'riesgo': 'Sobrecarga Postural debido a trabajo fuera del alcance funcional',
     'definicion': 'Trabajos que implican movimientos fuera del alcance funcional.'},
    {'codigo': 'T7', 'tipo': 'musculo',
     'familia': 'Sobrecarga Postural (postura mantenida y/o forzada)',
     'riesgo': 'Sobrecarga Postural debido a otras posturas',
     'definicion': 'Otras posturas no definidas en los ítems anteriores'},
    {'codigo': 'D1', 'tipo': 'psicosocial',
     'familia': 'Riesgos Psicosociales Laborales',
     'riesgo': 'Exigencias psicológicas en el trabajo',
     'definicion': 'Involucra exigencias emocionales, creativas y cuantitativas.'},
    {'codigo': 'D2', 'tipo': 'psicosocial',
     'familia': 'Riesgos Psicosociales Laborales',
     'riesgo': 'Trabajo activo y desarrollo de habilidades',
     'definicion': 'Se refiere a la autonomía del trabajador sobre su trabajo.'},
    {'codigo': 'D3', 'tipo': 'psicosocial',
     'familia': 'Riesgos Psicosociales Laborales',
     'riesgo': 'Apoyo social en la empresa y calidad del liderazgo',
     'definicion': 'Calidad del apoyo social y liderazgo dentro de la empresa.'},
    {'codigo': 'D4', 'tipo': 'psicosocial',
     'familia': 'Riesgos Psicosociales Laborales',
     'riesgo': 'Compensaciones',
     'definicion': 'Equilibrio entre esfuerzo y recompensas, estabilidad del empleo.'},
    {'codigo': 'D5', 'tipo': 'psicosocial',
     'familia': 'Riesgos Psicosociales Laborales',
     'riesgo': 'Doble presencia',
     'definicion': 'Preocupación por cumplir con tareas domésticas y laborales.'},
]


INDEX = {r['codigo']: r for r in RIESGOS}


def por_tipo(tipo):
    return [r for r in RIESGOS if r['tipo'] == tipo]


def agrupado():
    """[(familia, tipo, [riesgos])] en el orden del Anexo 2 — para pintar los <optgroup>."""
    out, vistas = [], {}
    for r in RIESGOS:
        k = r['familia']
        if k not in vistas:
            vistas[k] = {'familia': k, 'tipo': r['tipo'], 'riesgos': []}
            out.append(vistas[k])
        vistas[k]['riesgos'].append(r)
    return out


def buscar(texto):
    """Riesgos cuyo código, nombre o familia contengan el texto. Para el buscador del selector."""
    t = (texto or '').strip().lower()
    if not t:
        return []
    return [r for r in RIESGOS
            if t in r['codigo'].lower() or t in r['riesgo'].lower() or t in (r['familia'] or '').lower()]
