[theme]
primaryColor = "#27AAE1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F6FB"
textColor = "#0E3A5F"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
